import { ChapterMeta, TRACKS, TrackId } from './types'

export const tracks: readonly TrackId[] = TRACKS

export const chapters: ChapterMeta[] = [
  // P0 — Orientation
  {
    id: 'what-is-an-llm',
    title: 'What is an LLM, fundamentally?',
    part: 'P0',
    tracks: { beginner: 1, engineer: 1, automator: 1 },
    difficulty: 1,
    estMinutes: 12,
    tags: ['fundamentals', 'llm', 'tokens'],
    summary: 'Tokens, next-token prediction, context, and why models hallucinate — the mental model everything else builds on.',
  },
  {
    id: 'how-to-use-this-book',
    title: 'How to use this book & pick your path',
    part: 'P0',
    tracks: { beginner: 2, engineer: 2, automator: 2 },
    difficulty: 1,
    estMinutes: 6,
    tags: ['orientation', 'tracks', 'personas'],
    summary: 'How the three reader tracks share one chapter pool, how to switch paths, and how progress and resume work.',
  },
  {
    id: 'what-is-claude',
    title: 'What is Claude — the model family',
    part: 'P0',
    tracks: { beginner: 3, engineer: 3, automator: 3 },
    difficulty: 1,
    estMinutes: 10,
    tags: ['claude', 'models', 'opus-sonnet-haiku'],
    summary: 'The Opus/Sonnet/Haiku/Fable family, modalities, and what Claude is good and bad at.',
  },
  {
    id: 'what-is-claude-code',
    title: 'What is Claude Code — the agentic harness',
    part: 'P0',
    tracks: { beginner: 4, engineer: 4, automator: 4 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['claude-code', 'harness', 'mental-model'],
    summary: 'Why an agentic harness is a different mental model than a chat box — the loop that drives everything.',
  },
  // P1 — First Contact
  {
    id: 'install-first-session',
    title: 'Install & first session',
    part: 'P1',
    tracks: { beginner: 5, automator: 5 },
    difficulty: 1,
    estMinutes: 12,
    tags: ['install', 'cli', 'ide', 'setup'],
    summary: 'Getting Claude Code running across CLI, desktop, web, and IDE extensions, then starting your first session.',
  },
  {
    id: 'the-chat-loop',
    title: 'The chat loop',
    part: 'P1',
    tracks: { beginner: 6 },
    difficulty: 1,
    estMinutes: 8,
    tags: ['prompts', 'turns', 'basics'],
    summary: 'Prompts, turns, and reading responses — how a single back-and-forth with Claude actually works.',
  },
  {
    id: 'permissions-and-safety',
    title: 'Permissions, modes & safety',
    part: 'P1',
    tracks: { beginner: 7, automator: 6 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['permissions', 'safety', 'modes'],
    summary: 'What Claude can and can\'t touch, how to approve actions, and how to stay in control.',
  },
  {
    id: 'first-task-e2e',
    title: 'Your first real task, end to end',
    part: 'P1',
    tracks: { beginner: 8 },
    difficulty: 2,
    estMinutes: 15,
    tags: ['walkthrough', 'first-task', 'win'],
    summary: 'A small concrete win taken from start to finish to cement the workflow.',
  },
  // P2 — The Harness
  {
    id: 'agent-loop-anatomy',
    title: 'Anatomy of the agent loop',
    part: 'P2',
    tracks: { beginner: 9, engineer: 5 },
    difficulty: 2,
    estMinutes: 14,
    tags: ['agent-loop', 'system-prompt', 'tool-calls'],
    summary: 'System prompt, context, model, tool calls, results, repeat — the loop dissected node by node.',
  },
  {
    id: 'tool-surface',
    title: 'The tool surface',
    part: 'P2',
    tracks: { engineer: 6, automator: 7 },
    difficulty: 2,
    estMinutes: 16,
    tags: ['tools', 'read-write-edit', 'bash'],
    summary: 'Read/Write/Edit/Bash/Grep/Glob/Task/WebSearch and friends — what each does and when to reach for it.',
  },
  {
    id: 'permissions-modes-deep',
    title: 'Permissions & modes deep dive',
    part: 'P2',
    tracks: { engineer: 7 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['plan-mode', 'accept-edits', 'sandboxing'],
    summary: 'Plan mode, accept-edits, and sandboxing — the levers that trade safety for speed.',
  },
  {
    id: 'hooks',
    title: 'Hooks — automating harness behavior',
    part: 'P2',
    tracks: { engineer: 8, automator: 8 },
    difficulty: 3,
    estMinutes: 15,
    tags: ['hooks', 'sessionstart', 'pretooluse'],
    summary: 'SessionStart/PreToolUse/etc — scripting deterministic behavior into the harness itself.',
  },
  {
    id: 'slash-commands',
    title: 'Slash commands & built-ins',
    part: 'P2',
    tracks: { engineer: 9, automator: 9 },
    difficulty: 2,
    estMinutes: 10,
    tags: ['slash-commands', 'builtins'],
    summary: 'The built-in slash commands and how to add your own reusable shortcuts.',
  },
  {
    id: 'settings-env',
    title: 'Settings, env & config',
    part: 'P2',
    tracks: { engineer: 10, automator: 10 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['settings', 'config', 'env'],
    summary: 'settings.json, environment variables, and config layering across global and project scopes.',
  },
  // P3 — Context Engineering
  {
    id: 'context-window-budget',
    title: 'The context window & its budget',
    part: 'P3',
    tracks: { engineer: 11, automator: 11 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['context', 'budget', 'tokens'],
    summary: 'What\'s in the context window right now and how to reason about its token budget.',
  },
  {
    id: 'compaction-autocompact',
    title: 'Compaction & autocompact',
    part: 'P3',
    tracks: { engineer: 12 },
    difficulty: 3,
    estMinutes: 12,
    tags: ['compaction', 'autocompact', 'context'],
    summary: 'Why compaction triggers, what it costs you, and how to keep context lean.',
  },
  {
    id: 'memory-claude-md',
    title: 'Memory — CLAUDE.md & the remember pattern',
    part: 'P3',
    tracks: { engineer: 13, automator: 12 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['memory', 'claude-md', 'remember'],
    summary: 'CLAUDE.md, the memory tool, and the /remember pattern that persists knowledge across sessions.',
  },
  {
    id: 'long-running-no-bloat',
    title: 'Long-running tasks without context bloat',
    part: 'P3',
    tracks: { engineer: 14 },
    difficulty: 4,
    estMinutes: 16,
    tags: ['long-running', 'context-discipline', 'technique'],
    summary: 'The operator\'s real technique for sustaining big jobs without drowning the context window.',
  },
  {
    id: 'docs-as-context',
    title: 'Documentation as context',
    part: 'P3',
    tracks: { engineer: 15, automator: 13 },
    difficulty: 3,
    estMinutes: 12,
    tags: ['docs', 'context', 'grounding'],
    summary: 'Writing docs that make Claude measurably better at your codebase and domain.',
  },
  // P4 — Prompting & Spec Engineering
  {
    id: 'effective-prompting',
    title: 'Effective prompting for Claude',
    part: 'P4',
    tracks: { beginner: 10, engineer: 16, automator: 14 },
    difficulty: 2,
    estMinutes: 14,
    tags: ['prompting', 'specificity', 'examples'],
    summary: 'Specificity, examples, and structure — the prompt patterns that consistently get better output.',
  },
  {
    id: 'output-styles',
    title: 'Output styles & compression',
    part: 'P4',
    tracks: { engineer: 17 },
    difficulty: 2,
    estMinutes: 10,
    tags: ['output-styles', 'compression', 'caveman'],
    summary: 'Output styles like caveman and learning mode, and when compression pays off.',
  },
  {
    id: 'plan-an-idea',
    title: 'Planning an idea — brainstorm to spec to plan',
    part: 'P4',
    tracks: { engineer: 18, automator: 15 },
    difficulty: 3,
    estMinutes: 15,
    tags: ['planning', 'spec', 'superpowers'],
    summary: 'The brainstorm to spec to plan flow that turns a vague idea into an executable plan.',
  },
  {
    id: 'tdd-with-cheap-agents',
    title: 'TDD with low-cost agents',
    part: 'P4',
    tracks: { engineer: 19 },
    difficulty: 4,
    estMinutes: 16,
    tags: ['tdd', 'cheap-agents', 'dev-env'],
    summary: 'Test-driven development with low-cost agents and a dev environment built for fast loops.',
  },
  {
    id: 'what-claude-expects-trust',
    title: 'What Claude expects from you & building trust',
    part: 'P4',
    tracks: { beginner: 11, engineer: 20, automator: 16 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['delegation', 'trust', 'contract'],
    summary: 'The delegation contract — what you owe Claude and how trust is earned both directions.',
  },
  // P5 — Multi-Agent Orchestration
  {
    id: 'subagents',
    title: 'Subagents & the Agent tool',
    part: 'P5',
    tracks: { engineer: 21 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['subagents', 'agent-tool', 'delegation'],
    summary: 'What subagents are, how the Agent tool spawns them, and when to delegate.',
  },
  {
    id: 'parallel-agent-teams',
    title: 'Parallel agent teams',
    part: 'P5',
    tracks: { engineer: 22 },
    difficulty: 4,
    estMinutes: 16,
    tags: ['parallel', 'fan-out', 'orchestration'],
    summary: 'Fan-out across multiple agents — when it wins, when it hurts, and how to coordinate it.',
  },
  {
    id: 'workflows',
    title: 'Workflows — deterministic orchestration',
    part: 'P5',
    tracks: { engineer: 23 },
    difficulty: 4,
    estMinutes: 15,
    tags: ['workflows', 'pipeline', 'orchestration'],
    summary: 'Pipeline, parallel, and loop orchestration for repeatable multi-step jobs.',
  },
  {
    id: 'worktrees',
    title: 'Worktrees for isolation',
    part: 'P5',
    tracks: { engineer: 24 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['worktrees', 'isolation', 'git'],
    summary: 'Feature-per-worktree discipline that keeps parallel work from colliding.',
  },
  {
    id: 'cost-tiering',
    title: 'Cost-tiering — cheap for grunt, expensive for judgment',
    part: 'P5',
    tracks: { engineer: 25, automator: 17 },
    difficulty: 3,
    estMinutes: 12,
    tags: ['cost', 'model-choice', 'tiering'],
    summary: 'Matching model cost to task value — cheap agents for grunt work, expensive ones for judgment.',
  },
  // P6 — The Dev Workflow
  {
    id: 'offload-every-stage',
    title: 'Offloading every stage of dev',
    part: 'P6',
    tracks: { engineer: 26 },
    difficulty: 4,
    estMinutes: 16,
    tags: ['dev-workflow', 'offload', 'e2e'],
    summary: 'Explore, design, plan, TDD, implement, review, ship — handing each stage to Claude.',
  },
  {
    id: 'git-pr-cicd',
    title: 'Git, PRs & CI/CD with Claude',
    part: 'P6',
    tracks: { engineer: 27 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['git', 'pr', 'cicd'],
    summary: 'Driving commits, pull requests, and CI/CD pipelines through Claude without losing control.',
  },
  {
    id: 'code-review-panels',
    title: 'Code review — adversarial subagent panels',
    part: 'P6',
    tracks: { engineer: 28 },
    difficulty: 4,
    estMinutes: 15,
    tags: ['code-review', 'adversarial', 'verify'],
    summary: 'Adversarial subagent review panels and the verify-before-claim discipline.',
  },
  {
    id: 'case-study-feature-ship',
    title: 'Case study — how a feature actually ships',
    part: 'P6',
    tracks: { engineer: 29 },
    difficulty: 3,
    estMinutes: 18,
    tags: ['case-study', 'real-world', 'shipping'],
    summary: 'An anonymized walkthrough of a real feature from idea to merged, mined from real sessions.',
  },
  // P7 — Extending Claude
  {
    id: 'skills-use-write',
    title: 'Skills — using & writing',
    part: 'P7',
    tracks: { engineer: 30, automator: 18 },
    difficulty: 3,
    estMinutes: 15,
    tags: ['skills', 'authoring', 'extending'],
    summary: 'Finding and using skills, then writing your own to package repeatable expertise.',
  },
  {
    id: 'plugins-marketplaces',
    title: 'Plugins & marketplaces',
    part: 'P7',
    tracks: { engineer: 31, automator: 19 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['plugins', 'marketplaces', 'extending'],
    summary: 'Installing plugins, browsing marketplaces, and judging what\'s worth adding.',
  },
  {
    id: 'mcp-use-build',
    title: 'MCP — using servers & building your own',
    part: 'P7',
    tracks: { engineer: 32, automator: 20 },
    difficulty: 4,
    estMinutes: 18,
    tags: ['mcp', 'servers', 'integration'],
    summary: 'Connecting MCP servers and building your own to expose new tools to Claude.',
  },
  {
    id: 'api-agent-sdk',
    title: 'The Claude API & Agent SDK',
    part: 'P7',
    tracks: { engineer: 33 },
    difficulty: 4,
    estMinutes: 16,
    tags: ['api', 'agent-sdk', 'sdk'],
    summary: 'Calling the Claude API directly and building agents with the Agent SDK.',
  },
  {
    id: 'browser-ide-extensions',
    title: 'Browser & IDE extensions',
    part: 'P7',
    tracks: { engineer: 34, automator: 21 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['chrome', 'ide', 'extensions'],
    summary: 'Claude in Chrome and the IDE extensions — where each shines.',
  },
  {
    id: 'headless-cli',
    title: 'Headless / CLI automation',
    part: 'P7',
    tracks: { engineer: 35, automator: 22 },
    difficulty: 4,
    estMinutes: 15,
    tags: ['headless', 'cli', 'automation'],
    summary: 'Running Claude Code non-interactively for scripts, pipelines, and CI.',
  },
  // P8 — Automation & Integrations
  {
    id: 'automate-daily-tasks',
    title: 'Automating daily repetitive tasks',
    part: 'P8',
    tracks: { engineer: 36, automator: 23 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['automation', 'mindset', 'productivity'],
    summary: 'The mindset for spotting and offloading the small repetitive tasks that eat your day.',
  },
  {
    id: 'n8n-gsuite',
    title: 'n8n + GSuite patterns',
    part: 'P8',
    tracks: { automator: 24 },
    difficulty: 3,
    estMinutes: 18,
    tags: ['n8n', 'gsuite', 'gmail-drive-sheets'],
    summary: 'Wiring Claude to Gmail, Drive, Sheets, and Calendar through n8n workflows.',
  },
  {
    id: 'zapier-mcp',
    title: 'Zapier MCP & connecting SaaS',
    part: 'P8',
    tracks: { automator: 25 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['zapier', 'mcp', 'saas'],
    summary: 'Using Zapier MCP to connect Claude to thousands of SaaS apps.',
  },
  {
    id: 'scheduling',
    title: 'Scheduling — cron, loop & background tasks',
    part: 'P8',
    tracks: { engineer: 37, automator: 26 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['scheduling', 'cron', 'background'],
    summary: 'cron, loop, schedule, and background tasks for work that runs without you.',
  },
  {
    id: 'personal-automation-system',
    title: 'Building a personal automation system',
    part: 'P8',
    tracks: { automator: 27 },
    difficulty: 4,
    estMinutes: 18,
    tags: ['automation', 'system', 'personal'],
    summary: 'Assembling skills, schedules, and integrations into a coherent personal automation system.',
  },
  // P9 — Mastery & Power User
  {
    id: 'how-a-power-user-works',
    title: 'How a power user really works',
    part: 'P9',
    tracks: { engineer: 38, automator: 28 },
    difficulty: 4,
    estMinutes: 18,
    tags: ['power-user', 'case-study', 'patterns'],
    summary: 'Real patterns mined from thousands of sessions — how an effective operator actually works.',
  },
  {
    id: 'maximizing-performance',
    title: 'Maximizing performance',
    part: 'P9',
    tracks: { engineer: 39, automator: 29 },
    difficulty: 3,
    estMinutes: 14,
    tags: ['performance', 'model-choice', 'effort'],
    summary: 'Model choice, effort levels, and fast mode — knowing what to use when.',
  },
  {
    id: 'keeping-up-latest',
    title: 'Keeping up with the latest',
    part: 'P9',
    tracks: { beginner: 12, engineer: 40, automator: 30 },
    difficulty: 2,
    estMinutes: 12,
    tags: ['keeping-up', 'sources', 'ecosystem'],
    summary: 'Durable live sources and the newest repos, plugins, and skills worth trying.',
  },
  {
    id: 'delegation-maturity',
    title: 'Delegation maturity',
    part: 'P9',
    tracks: { engineer: 41, automator: 31 },
    difficulty: 3,
    estMinutes: 12,
    tags: ['delegation', 'trust', 'verification'],
    summary: 'Trust, verification, and knowing what to keep in your own hands as you scale delegation.',
  },
  // P10 — Reference
  {
    id: 'tool-reference',
    title: 'Tool reference',
    part: 'P10',
    tracks: { beginner: 13, engineer: 42, automator: 32 },
    difficulty: 1,
    estMinutes: 10,
    tags: ['reference', 'tools'],
    summary: 'A searchable catalog of every Claude Code tool — what, when, example, gotchas.',
  },
  {
    id: 'slash-command-reference',
    title: 'Slash-command reference',
    part: 'P10',
    tracks: { engineer: 43, automator: 33 },
    difficulty: 1,
    estMinutes: 8,
    tags: ['reference', 'slash-commands'],
    summary: 'A quick-lookup list of built-in slash commands and what they do.',
  },
  {
    id: 'glossary',
    title: 'Glossary',
    part: 'P10',
    tracks: { beginner: 14, engineer: 44, automator: 34 },
    difficulty: 1,
    estMinutes: 8,
    tags: ['reference', 'glossary'],
    summary: 'Plain-language definitions of the terms used throughout the book.',
  },
  {
    id: 'model-pricing-tables',
    title: 'Model & pricing cheat tables',
    part: 'P10',
    tracks: { engineer: 45, automator: 35 },
    difficulty: 1,
    estMinutes: 8,
    tags: ['reference', 'pricing', 'models'],
    summary: 'Model ids, capabilities, and current pricing in quick-reference tables.',
  },
  {
    id: 'links',
    title: 'Curated links',
    part: 'P10',
    tracks: { beginner: 15, engineer: 46, automator: 36 },
    difficulty: 1,
    estMinutes: 6,
    tags: ['reference', 'links', 'resources'],
    summary: 'A curated, durable set of links to official docs, repos, and ecosystem resources.',
  },
]

export function chapterById(id: string): ChapterMeta | undefined {
  return chapters.find(c => c.id === id)
}

export function chaptersForTrack(track: TrackId): ChapterMeta[] {
  return chapters
    .filter(c => c.tracks[track] !== undefined)
    .sort((a, b) => (a.tracks[track] ?? 0) - (b.tracks[track] ?? 0))
}
